resources:
  - https://raw.githubusercontent.com/apache/camel-k/release-2.1.x/config/crd/bases/camel.apache.org_pipes.yaml
  - https://raw.githubusercontent.com/apache/camel-k/release-2.1.x/config/crd/bases/camel.apache.org_kamelets.yaml
  - https://raw.githubusercontent.com/apache/camel-k/release-2.1.x/config/crd/bases/camel.apache.org_integrationplatforms.yaml
