name: Publish Release
on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    uses: ./.github/workflows/publish.yml
    with:
      version: "${{ github.ref_name }}"
    secrets:
      registry: "quay.io"
      registry-username: ${{ secrets.QUAY_USERNAME }}
      registry-password: ${{ secrets.QUAY_PASSWORD }}
