name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Go"
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: "Check"
        run: |
          make check
      - name: "Build"
        run: |
          make build
      - name: "Test"
        run: |
          make test
      - name: "SetUp KinD"
        uses: container-tools/kind-action@v2
        with:
          version: "v0.20.0"
          kubectl_version: v1.27.3
          registry: false
          node_image: kindest/node:v1.27.3
      - name: "e2e Test"
        run: |
          make test/apply-crds test/e2e
